name: CatTalk
description: "CatTalk is a mobile application that is aims for establishing social connectivity and enhancing the digital social experiences of Filipinos. Established with a focus on fostering genuine connections and providing a secure digital space, this project aims to be the go-to platform for Filipinos seeking a meaningful and rich social experience."

publish_to: "none"

version: 2.0.2+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # for using cupertino icons
  cupertino_icons: ^1.0.2
  # for using firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  # for logging in using google
  google_sign_in: ^6.2.1

  fluttertoast: ^8.2.4
  image_picker: ^1.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_local_notifications: ^16.1.0
  provider: ^6.1.1
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  flutter_easyloading: ^3.0.5
  emoji_picker_flutter: ^1.6.3
  http: ^1.1.2
  flutter_notification_channel: ^2.0.0
  gallery_saver_updated: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.3.0
  page_transition: ^2.1.0
  awesome_snackbar_content: ^0.1.3
  agora_uikit: ^1.3.7
  agora_rtc_engine: ^6.2.6
  flutter_facebook_auth: ^6.0.3
  agora_token_service: ^0.1.2
  file_picker: ^6.1.1
  swipe_to: ^1.0.5

dev_dependencies:
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
    
  flutter_lints: 2.0.3

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
