// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAau6tRuKR1CzP6nmMRQDYL9JPlEvoj6nM',
    appId: '1:545427152437:web:3c1d7aaad7e117d1ea5b7c',
    messagingSenderId: '545427152437',
    projectId: 'flutter-wechat-app',
    authDomain: 'flutter-wechat-app.firebaseapp.com',
    storageBucket: 'flutter-wechat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVY6Jg4_CXIV1PBE6dxUatXUSc6ZcB_I',
    appId: '1:545427152437:android:c94d53c4303a6f4dea5b7c',
    messagingSenderId: '545427152437',
    projectId: 'flutter-wechat-app',
    storageBucket: 'flutter-wechat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgCEan_Zo5bXcD6iB1iHLawIP_7Rln0o',
    appId: '1:545427152437:ios:378c2134b4b15687ea5b7c',
    messagingSenderId: '545427152437',
    projectId: 'flutter-wechat-app',
    storageBucket: 'flutter-wechat-app.appspot.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOgCEan_Zo5bXcD6iB1iHLawIP_7Rln0o',
    appId: '1:545427152437:ios:202a8ca6eaa755f2ea5b7c',
    messagingSenderId: '545427152437',
    projectId: 'flutter-wechat-app',
    storageBucket: 'flutter-wechat-app.appspot.com',
    iosBundleId: 'com.example.wechat.RunnerTests',
  );
}
